on: workflow_dispatch
#on:
#  workflow_dispatch:
#    inputs:
#      tags:
#        description: 'Test scenario tags'
#        required: false
#        type: boolean

jobs:
  build-resume:
    runs-on: ubuntu-latest

    steps:

    - uses: closoco/pdflatex-action@v1.0.0
    - run: sudo apt -y update; sudo apt -y install texlive-latex-base texlive-lang-cyrillic

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    - uses: actions/checkout@v3
    - run: python -m pip install --upgrade pip
    - run: pip install -r scripts/requirements.txt

#    - run: find / -name "t2aenc.def"

#andrey@andrey-pc:~$ find / -name "t2aenc.def"
#/usr/share/texlive/texmf-dist/tex/latex/cyrillic/t2aenc.def

    - run: mkdir output; pdflatex --enable-pipes --shell-escape -output-directory=output ./Threads-of-Fate.tex
